const hinos = {
  "622": "A beleza da tua santidade",
  "593": "A Cristo coroai",
  "614": "A Deus demos glória",
  "607": "A Deus seja o louvor",
  "722": "A Deus, supremo Criador",
  "682": "A Jesus seja dada toda glória",
  "402": "A lei do Senhor é perfeita",
  "641": "A luz do mundo",
  "35": "A meu Senhor",
  "624": "A minh'alma engrandece",
  "731-B": "A minh'alma está cheia de paz",
  "103": "A minh'alma estava longe do caminho do céu",
  "183": "A minha alegria",
  "174": "A minha herança é o Senhor",
  "422": "A minha herança",
  "449": "A minha vida entrego",
  "109": "A minha vida tão vazia",
  "753": "A noiva é a igreja",
  "278": "A nova do evangelho",
  "421": "A obra do Senhor é perfeita",
  "251": "A paz que tu procuras",
  "717": "A terra semeamos",
  "677": "A ti, que habitas entre os querubins",
  "450": "A tua justiça",
  "446": "A tua palavra",
  "559": "A última trombeta soará",
  "734": "A vida de minh'alma",
  "316": "A vida no mundo é cruel",
  "733-B": "A vida, a vida é Jesus",
  "768": "A vitória desta igreja é oração",
  "396": "Abba Pai",
  "773": "Abra a porta, venha ver",
  "779": "Abre a porta do teu coração",
  "116": "Achei salvação",
  "574": "Adorarei",
  "621": "Adorar-te",
  "646": "Agradecidos somos a ti",
  "276": "Ainda que os seus sonhos",
  "475": "Ainda uma vez (Ageu)",
  "653": "Aleluia (Sl 113)",
  "592": "Aleluia! Muitas vozes de anjos",
  "535": "Além do céu azul",
  "41": "Além do véu eu quero estar",
  "510": "Alerta povo, está chegando a nossa hora",
  "379": "Algemado por um peso",
  "293": "Alma cansada",
  "167": "Amo ao meu Senhor",
  "405": "Amo ao Senhor de todo o meu coração",
  "122": "Amo ao Senhor porque ele me ouviu"
};
