const hinos = [
  "622 - A beleza da tua santidade",
  "593 - A Cristo coroai",
  "614 - A Deus demos glória",
  "607 - A Deus seja o louvor",
  "722 - A Deus, supremo Criador",
  "682 - A Jesus seja dada toda glória",
  "402 - A lei do Senhor é perfeita",
  "641 - A luz do mundo",
  "35 - A meu Senhor",
  "624 - A minh'alma engrandece",
  "731-B - A minh'alma está cheia de paz",
  "103 - A minh'alma estava longe do caminho do céu",
  "183 - A minha alegria",
  "174 - A minha herança é o Senhor",
  "422 - A minha herança",
  "449 - A minha vida entrego",
  "109 - A minha vida tão vazia",
  "753 - A noiva é a igreja",
  "278 - A nova do evangelho",
  "421 - A obra do Senhor é perfeita",
  "251 - A paz que tu procuras",
  "717 - A terra semeamos",
  "677 - A ti, que habitas entre os querubins",
  "450 - A tua justiça",
  "446 - A tua palavra",
  "559 - A última trombeta soará",
  "734 - A vida de minh'alma",
  "316 - A vida no mundo é cruel",
  "733-B - A vida, a vida é Jesus",
  "768 - A vitória desta igreja é oração",
  "396 - Abba Pai",
  "773 - Abra a porta, venha ver",
  "779 - Abra a porta do teu coração",
  "116 - Achei salvação",
  "574 - Adorarei",
  "621 - Adorar-te",
  "646 - Agradecidos somos a ti",
  "276 - Ainda que os seus sonhos",
  "475 - Ainda uma vez (Ageu)",
  "653 - Aleluia (Sl 113)",
  "592 - Aleluia! Muitas vozes de anjos",
  "535 - Além do céu azul",
  "41 - Além do véu eu quero estar",
  "510 - Alerta povo, está chegando a nossa hora",
  "379 - Algemado por um peso",
  "293 - Alma cansada",
  "167 - Amo ao meu Senhor",
  "405 - Amo ao Senhor de todo o meu coração",
  "122 - Amo ao Senhor porque ele me ouviu",
  "651 - Amo ao Senhor",
  "689 - Amor, que por amor desceste!",
  "521 - Ao chegar ao céu gozo eu terei",
  "590 - Ao Cordeiro",
  "691 - Ao Deus de Abraão",
  "616 - Ao Deus de amor e de imensa bondade",
  "712 - Ao findar o labor desta vida (A última hora)",
  "543 - Ao lado de Deus",
  "542 - Ao lado de Jesus eu quero estar",
  "229 - Ao poço de Jacó chegou Jesus",
  "601 - Ao que está no trono",
  "292 - Ao sentir o mundo ao meu redor",
  "46 - Ao sentir o teu perdão",
  "790 - Aquele que habita no esconderijo",
  "403 - Aquele que tem os meus mandamentos",
  "CONTRA CAPA - Aquilo que fui não sou mais",
  "787 - Ardendo em fogo minh'alma está",
  "541 - Arrebatado fui no dia do Senhor",
  "720 - As grutas, as rochas imensas (Um hino ao Senhor)",
  "366 - As lágrimas falam, Jesus te escuta",
  "193 - As muitas águas não poderiam apagar",
  "140 - As muitas águas",
  "114 - As riquezas do mundo",
  "701 - As tuas mãos dirigem meu destino",
  "131 - Às vezes, alguém me pergunta",
  "481 - Assim como a noite espera pelo dia",
  "58 - Atende a voz do meu clamor",
  "84 - Atende, Senhor, a minha oração",
  "329 - Atua em nosso meio",
  "719 - Avante, avante, ó crentes",
  "288 - Basta dizeres o que queres",
  "304 - Basta que me toques, Senhor",
  "60 - Bem de manhã, embora o céu sereno",
  "384 - Bem sei que tudo podes",
  "94 - Bendita a hora de oração",
  "22 - Bendito seja o Cordeiro",
  "665 - Bendizei ao Senhor",
  "320 - Bom é o Senhor",
  "508 - Breve no céu Jesus há de aparecer",
  "534 - Breve voltará o Messias",
  "64 - Brilhe sobre mim",
  "95 - Buscar-me-eis",
  "97 - Buscou-me com ternura",
  "772 - Cada dia me dirige",
  "82 - Cada instante",
  "761 - Cada passo que dás",
  "771 - Caminhando vou para Canaã",
  "784 - Cantai ao Senhor um cântico novo",
  "550 - Cantai, ó igreja",
  "391 - Cantarei a bondade e a justiça",
  "390 - Cantarei a misericórdia",
  "582 - Cantarei ao amor dos amores",
  "618 - Cantarei ao meu Senhor enquanto eu viver",
  "780 - Cantarei, cantarei as misericórdias",
  "597 - Cantarei, cantarei hosana (Viva o Rei)",
  "713 - Careço de Jesus",
  "469 - Castelo forte",
  "659 - Celebrai com júbilo ao Senhor",
  "776 - Certa vez eu orando",
  "488 - Certa vez, ao orar",
  "215 - Certo homem tão nobre",
  "774 - Chegado a cruz do meu Salvador",
  "483 - Chegou o tempo de pensar",
  "572 - Cheguemos ao altar de Deus",
  "456 - Chuvas de bênçãos teremos",
  "5 - Clamando estou",
  "15 - Clamarei, clamarei",
  "3 - Clamo a ti",
  "96 - Com a minha voz clamo ao Senhor (Sl 142)",
  "714 - Com tua mão segura bem a minha (Amparo divino)",
  "692 - Comigo habita, ó Deus!",
  "169 - Como a flor do campo",
  "757 - Como aconteceu em Jerusalém",
  "777 - Como as águas",
  "430 - Como Cristo ensinou",
  "117 - Como desistir deste grande amor?",
  "732-F - Como é bom deixar este mundo",
  "199 - Como é bom ouvir tua voz",
  "182 - Como é bom servir ao Senhor",
  "573 - Como é bom te adorar",
  "493 - Como foi para o céu, Jesus Cristo há de vir",
  "401 - Como tu queres",
  "259 - Como um bom Pastor",
  "378 - Confia e ora",
  "344 - Confio em Deus",
  "44 - Conforme a tua infinita graça",
  "328 - Consolai, consolai o meu povo",
  "767 - Conta pra Jesus onde é a tua dor",
  "27 - Cordeiro eterno",
  "645 - Coroai",
  "211 - Cortaram o madeiro",
  "213 - Cristo caminhava em direção à cruz",
  "261 - Cristo caminhava lentamente",
  "736 - Cristo é a resposta",
  "157 - Cristo é a rosa mais bela",
  "147 - Cristo é tudo para mim",
  "431 - Cristo já nos preparou",
  "688 - Cristo já ressuscitou",
  "151 - Cristo Jesus é o meu bom Salvador",
  "354 - Cristo me dará",
  "723 - Cristo pode hoje vir (Oh! Dia alegre!)",
  "498 - Cristo vem me buscar",
  "142 - Cristo, meu Mestre, sempre há de amar-me",
  "153 - Cristo, nome mais alto",
  "36 - Crucificado foi meu Jesus",
  "690 - Da igreja o fundamento é Cristo (A Pedra fundamental)",
  "555 - Da linda pátria",
  "613 - Dai glória a Deus",
  "364 - Dá-me mais fé",
  "89 - Das profundezas clamo a ti, ó Senhor!",
  "88 - Das profundezas",
  "295 - Das profundezas, a ti clamo, ó Senhor",
  "66 - De madrugada eu busco a face do Senhor",
  "750 - Deixa a glória de Deus brilhar",
  "239 - Deixa Deus falar ao teu coração",
  "353 - Deixa-me chorar",
  "217 - Deixou o esplendor de sua glória",
  "189 - Dependo de ti, Senhor",
  "440 - Derramarei meu Espírito",
  "731-A - Desde o dia em que aceitei Jesus",
  "175 - Desde o dia em que te conheci",
  "444 - Desejei ardentemente",
  "706 - (Grandes coisas fez o Senhor por nós)",
  "208 - Deus amou o mundo de tal maneira",
  "334 - Deus cuida de ti",
  "669 - Deus dos antigos",
  "608 - Deus dos exércitos de Israel",
  "327 - Deus é contigo",
  "377 - Deus é minha rocha",
  "359 - Deus é nosso amparo, nossa fortaleza",
  "207 - Deus enviou seu filho amado",
  "778 - Deus está aqui",
  "73 - Deus está no templo",
  "260 - Deus está presente aqui neste lugar",
  "79 - Deus está presente entre pecadores como nós",
  "323 - Deus está presente sempre pronto a nos ajudar",
  "234 - Deus hoje quer te falar",
  "209 - Deus o seu Filho enviou",
  "362 - Deus proverá",
  "340 - Deus te guardará",
  "715 - Deus vos guarde pelo seu poder",
  "625 - Digno é Jesus",
  "445 - Dirige-me, Senhor",
  "564 - Dispõe-te, resplandece",
  "338 - Divino companheiro",
  "760 - Do céu virá",
  "486 - Do norte vem o áureo esplendor",
  "214 - Dois discípulos no caminho de Emaús",
  "693 - Dormindo no meu leito (Jerusalém, cidade santa)",
  "164 - É bastante para mim a tua graça",
  "745 - É Deus quem nos tem dado a vitória",
  "731-E - É isto que me faz cantar",
  "145 - É o amor de Deus",
  "72 - É preciso confiar e buscar a Deus",
  "459 - É tempo, é tempo",
  "47 - É teu sangue",
  "679 - Eis a escrava resgatada",
  "330 - Eis aí o dia aceitável",
  "409 - Eis marchamos para aquele bom país",
  "237 - Eis mensagem do Senhor",
  "24 - Eis o Cordeiro de Deus",
  "466 - Eis o estandarte",
  "724 - Eis os milhões",
  "727 - Eis que abro a porta",
  "560 - Eis que estou à porta e bato",
  "222 - Eis que estou à porta",
  "408 - Eis que surge um povo forte",
  "198 - Ele é a minha alegria",
  "159 - Ele é a rosa de Sarom",
  "684 - Ele é o Rei dos reis",
  "491 - Ele um dia voltará",
  "490 - Ele voltará pra buscar a sua igreja",
  "492 - Ele voltará, sim, ele voltará",
  "489 - Em breve escutarei",
  "544 - Em breve o dia chegará",
  "509 - Em breve, mui breve",
  "57 - Em fervente oração",
  "297 - Em me vindo o temor",
  "135 - Em meu coração",
  "345 - Em nada ponho a minha fé",
  "642 - Em nossos lábios",
  "14 - Em teu altar, Senhor",
  "86 - Em teu nome",
  "181 - Em ti eu encontro, ó Deus, toda paz",
  "17 - Em tua presença entramos",
  "90 - Em tuas mãos, Senhor",
  "180 - Encontrei o grande amor",
  "716 - Enquanto, ó Salvador, teu livro ler",
  "228 - Entrega o teu caminho ao Senhor",
  "398 - Entrei no tempo de Deus",
  "635 - Entronizado está entre as nações",
  "85 - Envia a tua luz",
  "224 - Era um pecador, andava sem Jesus",
  "161 - Era uma oliveira",
  "596 - És majestade",
  "661 - És o mais formoso, Jesus",
  "429 - És o pão da vida",
  "52 - Escuta-me, Senhor",
  "368 - Esforça-te, tem bom ânimo!",
  "348 - Espera no Senhor, anima-te",
  "436 - Espírito do trino Deus",
  "441 - Espírito Santo, ó consolador",
  "758 - Esta alegria não vai mais sair",
  "514 - Esta é a voz, a voz do meu amado",
  "476 - Esta obra é de Deus",
  "136 - Esta paz que sinto em minh'alma",
  "395 - Fala, Jesus querido",
  "350 - Faz-me inabalável",
  "129 - Felicidade é ter Cristo ao meu lado",
  "783 - Feliz, feliz eu sou",
  "536 - Finda a lida terreal",
  "347 - Firme nas promessas",
  "435 - Fluirá como um rio",
  "585 - Fonte da vida",
  "230 - Fonte de águas vivas",
  "577 - Glória e aleluia",
  "591 - Glória pra sempre ao Cordeiro de Deus",
  "738 - Glória, glória",
  "634 - Glorioso és, Jesus",
  "731-F - Gozo eu tenho em Jesus",
  "115 - Graças dou, ó Senhor",
  "195 - Grande amor, ó grande amor",
  "81 - Grande Deus, único Deus",
  "654 - Grande é o Senhor e mui digno de ser louvado",
  "656 - Grande é o Senhor",
  "705 - Grandes são, Senhor, os teus feitos! (Gratidão)",
  "162 - Grandioso para mim",
  "718 - Guia, ó Cristo, minha nau",
  "336 - Há alguém que cuida de ti",
  "280 - Há hoje alguém esperando",
  "299 - Há momentos que as palavras não resolvem",
  "138 - Há sempre alguém que não provou",
  "468 - Há tanta terra",
  "322 - Há um amigo sempre junto",
  "434 - Há um doce Espírito aqui",
  "525 - Há um lindo país",
  "538 - Há um lugar pra mim",
  "688 - Há um nome que reluz",
  "418 - Há um povo que te adora",
  "443 - Há um rio de águas vivas",
  "155 - Há um ser que vive em mim",
  "598 - Há um só que é digno",
  "202 - Há uma fonte aberta no Calvário",
  "397 - Há uma luz a brilhar",
  "419 - Há uma obra que Deus quer fazer",
  "12 - Há vitória para mim",
  "64 - Há vitória sempre em ti, Senhor",
  "578 - Hoje o Senhor derramou",
  "197 - Hoje quero somente agradecer",
  "788 - Igreja, tu vais subir",
  "457 - Instrumento em tuas mãos",
  "63 - Invoca-me e te responderei",
  "108 - Israel saiu do Egito",
  "243 - Já achei uma flor gloriosa",
  "382 - Já cheguei até aqui (Vitórias)",
  "132 - Já não estou sozinho",
  "517 - Já não tarda o amanhecer",
  "570 - Já refulge a glória eterna (Vencendo vem Jesus!)",
  "694 - Jerusalém eterna",
  "695 - Jerusalém excelsa",
  "531 - Jerusalém, Jerusalém",
  "554 - Jerusalém (Suas ruas de ouro)",
  "120 - Jesus Cristo mudou meu viver",
  "683 - Jesus Cristo voltará",
  "511 - Jesus Cristo voltará com seu grande esplendor",
  "611 - Jesus, Deus santo, santo, santo!",
  "370 - Jesus é a rocha inabalável",
  "731-G - Jesus é maravilhoso!",
  "225 - Jesus é melhor, sim, que ouro e bens",
  "746 - Jesus é o amigo melhor",
  "268 - Jesus é o Cordeiro",
  "763 - Jesus é tudo pra mim",
  "545 - Jesus está às portas",
  "149 - Jesus fez a promessa",
  "294 - Jesus ia caminhando (Canta meu povo)",
  "205 - Jesus ia seguindo",
  "203 - Jesus ia subindo o monte",
  "794 - Jesus libertou",
  "589 - Jesus tão belo",
  "638 - Jesus veio e salvou-me",
  "569 - Jesus vem! Vem nos buscar!",
  "113 - Jesus, a luz divina",
  "91 - Jesus, a minh'alma tem sede de ti",
  "144 - Jesus, agora eu bem sei",
  "221 - Jesus, em tua presença",
  "192 - Jesus, Jesus, eu te amo",
  "119 - Jesus, nome precioso",
  "158 - Jesus, o lírio dos vales",
  "6 - Jesus, ó meu Jesus",
  "406 - Jesus, o que eu mais quero no mundo",
  "404 - Jesus, quero amar-te",
  "185 - Jesus, Senhor, me chego a ti (Eu venho como estou)",
  "497 - Jesus, sim, vem, do céu em glória ele vem",
  "600 - Jesus, te entronizamos",
  "599 - Jesus, te entronizamos aqui entre nós",
  "39 - Jesus, tu és o meu Deus",
  "31 - Junto a ti suplico, ó Pai",
  "539 - Junto ao trono de Deus, preparado",
  "667 - Justo és, Senhor",
  "565 - Lá está o meu tesouro",
  "523 - Lá no céu os anjos cantam",
  "765 - Lá no céu todos cantam aleluia",
  "68 - Lá no cimo do monte",
  "383 - Lá onde eu não posso ver (A oração)",
  "265 - Leva tu contigo o nome",
  "652 - Levantai-vos, ó portais eternos",
  "526 - Lindo! Lindo! Lindo!",
  "93 - Logo de manhã",
  "636 - Louvai a Jesus",
  "663 - Louvai ao Senhor todas as nações",
  "655 - Louvai, servos do Senhor",
  "644 - Louvamos-te, ó Deus",
  "792 - Louvando a Deus (At 2.47)",
  "603 - Louvarei ao meu Senhor",
  "615 - Louvor e glória",
  "442 - Mais do teu Santo Espírito",
  "152 - Mais perto de Jesus",
  "319 - Mais perto quero estar",
  "83 - Mais uma vez",
  "595 - Majestade, glória e majestade",
  "749 - Manda fogo, Senhor",
  "235 - Manso e suave Jesus está chamando",
  "165 - Maravilhosa graça",
  "102 - Maravilhoso e sublime pra mim",
  "549 - Maravilhoso será",
  "658 - Meditarei nas maravilhas do Senhor",
  "306 - Medo tens que o tentador te vá vencer?",
  "793 - Mesa preparada",
  "310 - Mestre, o mar se revolta",
  "241 - Meu amado filho",
  "733-C - Meu coração contente está",
  "255 - Meu coração engrandece ao Senhor (Cântico de vitória!)",
  "381 - Meu Deus vence batalhas",
  "414 - Meu Deus, meu bom Pastor",
  "640 - Meu louvor é só pra ti",
  "87 - Meu pecado resgatado",
  "672 - Meu servo, não temas",
  "187 - Minh'alma tem sede de ti",
  "533 - Minha alma, pois, alegre canta",
  "417 - Minha dedicação",
  "473 - Minha porção",
  "204 - Morri na cruz por ti",
  "639 - Motivos tenho pra louvar-te",
  "632 - Muitos anjos louvam",
  "372 - Muitos são os que confiam",
  "731-D - Na casa de meu Pai não há tristeza",
  "675 - Na eternidade",
  "594 - Na expressão deste louvor",
  "49 - Na hora em que eu quiser falar com Deus",
  "556 - Na nova Jerusalém irei morar",
  "789 - Na presença de Jesus",
  "696 - Na terra abençoada",
  "335 - Não desanimes! Deus proverá",
  "176 - Não existe outro amor igual ao teu, Senhor",
  "220 - Não há amor igual",
  "361 - Não há Deus acima do Senhor",
  "741 - Não há Deus tão grande como tu",
  "256 - Não mais vivo eu, mas Cristo vive em mim",
  "563 - Não se turbem os vossos corações",
  "139 - Não sei por que de Deus o amor",
  "494 - Não sei quando Cristo Jesus há de vir",
  "269 - Não sei se ouviste falar",
  "365 - Não temas, pois te escolhi (Quando pelas águas)",
  "518 - Não terei mais tristezas",
  "287 - Não tinha parecer",
  "496 - Não vai tardar",
  "548 - Nas lindas moradas",
  "298 - Nem sempre entendemos",
  "21 - Nesta hora de clamor",
  "7 - Nesta hora em oração",
  "37 - Nesta hora esqueço o mundo",
  "76 - Nesta noite feliz",
  "742 - No céu há janelas abertas",
  "766 - No dia da grande glória",
  "470 - No Getsêmani",
  "451 - No serviço do meu Rei eu sou feliz",
  "62 - No silêncio da noite",
  "520 - No trono da cidade de Deus",
  "45 - Nos átrios do Senhor entramos",
  "580 - Nos prostremos aos seus pés",
  "627 - Nós te adoramos, Senhor",
  "764 - Nós vamos lá, irmãos",
  "728 - Nossa gratidão",
  "605 - Nosso Deus é soberano",
  "681 - Nosso louvor",
  "272 - Novo caminho",
  "759 - Nunca mais, nunca mais",
  "166 - Ó amado de minh'alma",
  "284 - O amor de Deus é grande",
  "141 - O amor de Deus por nós",
  "171 - O amor de Jesus é grande",
  "69 - O anjo do Senhor está passeando",
  "271 - O caminho que nos leva ao céu é Jesus",
  "762 - O céu é um lugar maravilhoso",
  "51 - O Cordeiro que na cruz morreu",
  "606 - O Criador do universo",
  "458 - Ó Cristo! Pão da vida",
  "178 - O Deus a quem servimos",
  "501 - O Espírito de Deus fala à sua igreja",
  "438 - O Espírito do Senhor está sendo derramado",
  "465 - O estandarte desta igreja",
  "196 - O grande amor do meu Senhor",
  "583 - Ó grande Deus",
  "571 - O grande dia está chegando",
  "769 - O grande relógio",
  "460 - Ó Jesus! Ó vera Páscoa",
  "587 - Ó Jesus, exaltar-te-ei",
  "337 - O mesmo Deus",
  "424 - O meu amado desceu ao seu jardim",
  "512 - O meu amado fala e me diz",
  "617 - O meu coração se regozija no Senhor",
  "660 - O meu coração",
  "604 - O meu louvor é fruto",
  "710 - O meu viver é Cristo",
  "283 - O mundo não sabe",
  "732-E - O nome de Jesus é doce",
  "673 - Ó Pai, eu queria tanto ver (Autor da minha fé)",
  "423 - Ó Pastor de Israel",
  "28 - O poder do sangue de Jesus",
  "111 - O povo que andava em trevas",
  "586 - Ó profundidade das riquezas",
  "495 - O que há de vir, virá",
  "313 - O que habita no abrigo de Deus",
  "290 - O que os olhos nunca viram",
  "332 - O Rei e eu",
  "2 - O sangue de Jesus tem poder para salvar",
  "1 - O sangue de Jesus tem poder",
  "50 - O sangue de Jesus",
  "32 - O sangue de Jesus, vertido ali na cruz",
  "53 - O sangue do Cordeiro de Deus",
  "411 - O Senhor da ceifa está chamando",
  "273 - O Senhor é a alegria",
  "305 - O Senhor é a minha luz",
  "357 - O Senhor é o meu Pastor (Bondade e misericórdia)",
  "566 - O Senhor é o meu Pastor (Maranata, Jesus vem)",
  "648 - O Senhor é o meu Pastor (Minh'alma cantará)"
];

