const hinos = [
  "622 - A beleza da tua santidade",
  "593 - A Cristo coroai",
  "614 - A Deus demos glória",
  "607 - A Deus seja o louvor",
  "722 - A Deus, supremo Criador",
  "682 - A Jesus seja dada toda glória",
  "402 - A lei do Senhor é perfeita",
  "641 - A luz do mundo",
  "35 - A meu Senhor",
  "624 - A minh'alma engrandece",
  "731-B - A minh'alma está cheia de paz",
  "103 - A minh'alma estava longe do caminho do céu",
  "183 - A minha alegria",
  "174 - A minha herança é o Senhor",
  "422 - A minha herança",
  "449 - A minha vida entrego",
  "109 - A minha vida tão vazia",
  "753 - A noiva é a igreja",
  "278 - A nova do evangelho",
  "421 - A obra do Senhor é perfeita",
  "251 - A paz que tu procuras",
  "717 - A terra semeamos",
  "677 - A ti, que habitas entre os querubins",
  "450 - A tua justiça",
  "446 - A tua palavra",
  "559 - A última trombeta soará",
  "734 - A vida de minh'alma",
  "316 - A vida no mundo é cruel",
  "733-B - A vida, a vida é Jesus",
  "768 - A vitória desta igreja é oração",
  "396 - Abba Pai",
  "773 - Abra a porta, venha ver",
  "779 - Abra a porta do teu coração",
  "116 - Achei salvação",
  "574 - Adorarei",
  "621 - Adorar-te",
  "646 - Agradecidos somos a ti",
  "276 - Ainda que os seus sonhos",
  "475 - Ainda uma vez (Ageu)",
  "653 - Aleluia (Sl 113)",
  "592 - Aleluia! Muitas vozes de anjos",
  "535 - Além do céu azul",
  "41 - Além do véu eu quero estar",
  "510 - Alerta povo, está chegando a nossa hora",
  "379 - Algemado por um peso",
  "293 - Alma cansada",
  "167 - Amo ao meu Senhor",
  "405 - Amo ao Senhor de todo o meu coração",
  "122 - Amo ao Senhor porque ele me ouviu",
  "651 - Amo ao Senhor",
  "689 - Amor, que por amor desceste!",
  "521 - Ao chegar ao céu gozo eu terei",
  "590 - Ao Cordeiro",
  "691 - Ao Deus de Abraão",
  "616 - Ao Deus de amor e de imensa bondade",
  "712 - Ao findar o labor desta vida (A última hora)",
  "543 - Ao lado de Deus",
  "542 - Ao lado de Jesus eu quero estar",
  "229 - Ao poço de Jacó chegou Jesus",
  "601 - Ao que está no trono",
  "292 - Ao sentir o mundo ao meu redor",
  "46 - Ao sentir o teu perdão",
  "790 - Aquele que habita no esconderijo",
  "403 - Aquele que tem os meus mandamentos",
  "CONTRA CAPA - Aquilo que fui não sou mais",
  "787 - Ardendo em fogo minh'alma está",
  "541 - Arrebatado fui no dia do Senhor",
  "720 - As grutas, as rochas imensas (Um hino ao Senhor)",
  "366 - As lágrimas falam, Jesus te escuta",
  "193 - As muitas águas não poderiam apagar",
  "140 - As muitas águas",
  "114 - As riquezas do mundo",
  "701 - As tuas mãos dirigem meu destino",
  "131 - Às vezes, alguém me pergunta",
  "481 - Assim como a noite espera pelo dia",
  "58 - Atende a voz do meu clamor",
  "84 - Atende, Senhor, a minha oração",
  "329 - Atua em nosso meio",
  "719 - Avante, avante, ó crentes",
  "288 - Basta dizeres o que queres",
  "304 - Basta que me toques, Senhor",
  "60 - Bem de manhã, embora o céu sereno",
  "384 - Bem sei que tudo podes",
  "94 - Bendita a hora de oração",
  "22 - Bendito seja o Cordeiro",
  "665 - Bendizei ao Senhor",
  "320 - Bom é o Senhor",
  "508 - Breve no céu Jesus há de aparecer",
  "534 - Breve voltará o Messias",
  "64 - Brilhe sobre mim",
  "95 - Buscar-me-eis",
  "97 - Buscou-me com ternura",
  "772 - Cada dia me dirige",
  "82 - Cada instante",
  "761 - Cada passo que dás",
  "771 - Caminhando vou para Canaã",
  "784 - Cantai ao Senhor um cântico novo",
  "550 - Cantai, ó igreja",
  "391 - Cantarei a bondade e a justiça",
  "390 - Cantarei a misericórdia",
  "582 - Cantarei ao amor dos amores",
  "618 - Cantarei ao meu Senhor enquanto eu viver",
  "780 - Cantarei, cantarei as misericórdias",
  "597 - Cantarei, cantarei hosana (Viva o Rei)",
  "713 - Careço de Jesus",
  "469 - Castelo forte",
  "659 - Celebrai com júbilo ao Senhor",
  "776 - Certa vez eu orando",
  "488 - Certa vez, ao orar",
  "215 - Certo homem tão nobre",
  "774 - Chegado a cruz do meu Salvador",
  "483 - Chegou o tempo de pensar",
  "572 - Cheguemos ao altar de Deus",
  "456 - Chuvas de bênçãos teremos",
  "5 - Clamando estou",
  "15 - Clamarei, clamarei",
  "3 - Clamo a ti",
  "96 - Com a minha voz clamo ao Senhor (Sl 142)",
  "714 - Com tua mão segura bem a minha (Amparo divino)",
  "692 - Comigo habita, ó Deus!",
  "169 - Como a flor do campo",
  "757 - Como aconteceu em Jerusalém",
  "777 - Como as águas",
  "430 - Como Cristo ensinou",
  "117 - Como desistir deste grande amor?",
  "732-F - Como é bom deixar este mundo",
  "199 - Como é bom ouvir tua voz",
  "182 - Como é bom servir ao Senhor",
  "573 - Como é bom te adorar",
  "493 - Como foi para o céu, Jesus Cristo há de vir",
  "401 - Como tu queres",
  "259 - Como um bom Pastor",
  "378 - Confia e ora",
  "344 - Confio em Deus",
  "44 - Conforme a tua infinita graça",
  "328 - Consolai, consolai o meu povo",
  "767 - Conta pra Jesus onde é a tua dor",
  "27 - Cordeiro eterno",
  "645 - Coroai",
  "211 - Cortaram o madeiro",
  "213 - Cristo caminhava em direção à cruz",
  "261 - Cristo caminhava lentamente",
  "736 - Cristo é a resposta",
  "157 - Cristo é a rosa mais bela",
  "147 - Cristo é tudo para mim",
  "431 - Cristo já nos preparou",
  "688 - Cristo já ressuscitou",
  "151 - Cristo Jesus é o meu bom Salvador",
  "354 - Cristo me dará",
  "723 - Cristo pode hoje vir (Oh! Dia alegre!)",
  "498 - Cristo vem me buscar",
  "142 - Cristo, meu Mestre, sempre há de amar-me",
  "153 - Cristo, nome mais alto",
  "36 - Crucificado foi meu Jesus",
  "690 - Da igreja o fundamento é Cristo (A Pedra fundamental)",
  "555 - Da linda pátria",
  "613 - Dai glória a Deus",
  "364 - Dá-me mais fé",
  "89 - Das profundezas clamo a ti, ó Senhor!",
  "88 - Das profundezas",
  "295 - Das profundezas, a ti clamo, ó Senhor",
  "66 - De madrugada eu busco a face do Senhor",
  "750 - Deixa a glória de Deus brilhar",
  "239 - Deixa Deus falar ao teu coração",
  "353 - Deixa-me chorar",
  "217 - Deixou o esplendor de sua glória",
  "189 - Dependo de ti, Senhor",
  "440 - Derramarei meu Espírito",
  "731-A - Desde o dia em que aceitei Jesus",
  "175 - Desde o dia em que te conheci",
  "444 - Desejei ardentemente",
  "706 - (Grandes coisas fez o Senhor por nós)",
  "208 - Deus amou o mundo de tal maneira",
  "334 - Deus cuida de ti",
  "669 - Deus dos antigos",
  "608 - Deus dos exércitos de Israel",
  "327 - Deus é contigo",
  "377 - Deus é minha rocha",
  "359 - Deus é nosso amparo, nossa fortaleza",
  "207 - Deus enviou seu filho amado",
  "778 - Deus está aqui",
  "73 - Deus está no templo",
  "260 - Deus está presente aqui neste lugar",
  "79 - Deus está presente entre pecadores como nós",
  "323 - Deus está presente sempre pronto a nos ajudar",
  "234 - Deus hoje quer te falar",
  "209 - Deus o seu Filho enviou",
  "362 - Deus proverá",
  "340 - Deus te guardará",
  "715 - Deus vos guarde pelo seu poder",
  "625 - Digno é Jesus",
  "445 - Dirige-me, Senhor",
  "564 - Dispõe-te, resplandece",
  "338 - Divino companheiro",
  "760 - Do céu virá",
  "486 - Do norte vem o áureo esplendor",
  "214 - Dois discípulos no caminho de Emaús",
  "693 - Dormindo no meu leito (Jerusalém, cidade santa)",
  "164 - É bastante para mim a tua graça",
  "745 - É Deus quem nos tem dado a vitória",
  "731-E - É isto que me faz cantar",
  "145 - É o amor de Deus",
  "72 - É preciso confiar e buscar a Deus",
  "459 - É tempo, é tempo",
  "47 - É teu sangue",
  "679 - Eis a escrava resgatada",
  "330 - Eis aí o dia aceitável",
  "409 - Eis marchamos para aquele bom país",
  "237 - Eis mensagem do Senhor",
  "24 - Eis o Cordeiro de Deus",
  "466 - Eis o estandarte",
  "724 - Eis os milhões",
  "727 - Eis que abro a porta",
  "560 - Eis que estou à porta e bato",
  "222 - Eis que estou à porta",
  "408 - Eis que surge um povo forte",
  "198 - Ele é a minha alegria",
  "159 - Ele é a rosa de Sarom",
  "684 - Ele é o Rei dos reis",
  "491 - Ele um dia voltará",
  "490 - Ele voltará pra buscar a sua igreja",
  "492 - Ele voltará, sim, ele voltará",
  "489 - Em breve escutarei",
  "544 - Em breve o dia chegará",
  "509 - Em breve, mui breve",
  "57 - Em fervente oração",
  "297 - Em me vindo o temor",
  "135 - Em meu coração",
  "345 - Em nada ponho a minha fé",
  "642 - Em nossos lábios",
  "14 - Em teu altar, Senhor",
  "86 - Em teu nome",
  "181 - Em ti eu encontro, ó Deus, toda paz",
  "17 - Em tua presença entramos",
  "90 - Em tuas mãos, Senhor",
  "180 - Encontrei o grande amor",
  "716 - Enquanto, ó Salvador, teu livro ler",
  "228 - Entrega o teu caminho ao Senhor",
  "398 - Entrei no tempo de Deus",
  "635 - Entronizado está entre as nações",
  "85 - Envia a tua luz",
  "224 - Era um pecador, andava sem Jesus",
  "161 - Era uma oliveira",
  "596 - És majestade",
  "661 - És o mais formoso, Jesus",
  "429 - És o pão da vida",
  "52 - Escuta-me, Senhor",
  "368 - Esforça-te, tem bom ânimo!",
  "348 - Espera no Senhor, anima-te",
  "436 - Espírito do trino Deus",
  "441 - Espírito Santo, ó consolador",
  "758 - Esta alegria não vai mais sair",
  "514 - Esta é a voz, a voz do meu amado",
  "476 - Esta obra é de Deus",
  "136 - Esta paz que sinto em minh'alma",
];
